name: Build and Deploy Nx Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-main-app:
    name: Build main-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build main-app
        run: npx nx run main-app:build --verbose

      - name: Trigger Render Deploy Hook (main-app)
        if: success()
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_MAIN_APP }}

  # build-e-commerce:
  #   name: Build e-commerce
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 22

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Build e-commerce
  #       run: npx nx run e-commerce:build --verbose

  #     - name: Trigger Render Deploy Hook (e-commerce)
  #       if: success()
  #       run: |
  #         curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_ECOMMERCE }}